<?php
# ex: set ts=2 et:

/*
$Bugs['chinook-helicopter-crash'] = array(
  'title' => 'Chinook Helicopter Crash',
  'when' => 'Jun 2, 1994',
  'industry' => 'military',
  'result' => array(
  ),
  'cost' => array(
    'deaths' => 29,
    'injuries' => 0,
    'dollars' => null,
  ),
  'causes' => array(
    '' => null,
  ),
  'mitigating' => array(
  ),
  'refs' => array(
    array(
      'title'     => 'The Chinook Helicopter Disaster',
      'author'    => 'Prof. Simon Rogerson',
      'url'       => 'http://www.ccsr.cse.dmu.ac.uk/resources/general/ethicol/Ecv12no2.html',
    ),
  ),
);
*/

