<?php
# ex: set ts=2 et:

$Bugs['cryosat-1'] = array(
  'title' => 'Cryosat-1',
  'when' => '2005',
  'industry' => 'aerospace',
  'result' => array(
    'rocket/satellite loss' => 1,
  ),
  'cost' => array(
    'deaths' => 0,
    'injuries' => 0,
    'dollars' => 186e6,
    '€€' => 140e6,
  ),
  'causes' => array(
    '"missing command"' => 2,
    'insufficient review' => 2,
  ),
  'mitigating' => array(
  ),
  'refs' => array(
    array(
      'title'     => 'CryoSat-1',
      'author'    => 'Wikipedia',
      'url'       => 'http://en.wikipedia.org/wiki/CryoSat-1',
    ),
    array(
      'title'     => 'CryoSat Mission lost due to launch failure',
      'author'    => 'European Space Agency',
      'url'       => 'http://www.esa.int/esaLP/SEMR3Q5Y3EE_LPcryosat_0.html',
    ),
  ),
);

