<?php
# ex: set ts=2 et:

$Bugs[basename(__FILE__)] = array(
  'title' => "Excel '65535' Display Bug",
  'when' => '2007',
  'industry' => 'software',
  'summary' => '',
  'result' => array(
  ),
  'cost' => array(
    'deaths' => 0,
    'injuries' => 0,
    'dollars' => null,
  ),
  'causes' => array(
  ),
  'mitigating' => array(
  ),
  'refs' => array(
    array(
      'title'     => "What's 77.1 x 850? Don't ask Excel 2007",
      'author'    => 'Dan Goodin',
      'url'       => 'http://www.theregister.co.uk/2007/09/26/excel_2007_bug/',
    ),
  ),
);

