<?php
# ex: set ts=2 et:

$Bugs['f-22-raptor-dateline'] = array(
  'title' => 'F-22 Raptor International Dateline Crossing',
  'when' => 'Feb 11, 2007',
  'industry' => 'military',
  'summary' => "",
  'result' => array(
    'complete system crash' => 3,
    'mission aborted' => 3,
    'retreated by visually following tankers' => 3,
  ),
  'cost' => array(
    'deaths' => 0,
    'injuries' => 0,
    'lives-at-risk' => 6,
    'dollars' => null,
  ),
  'causes' => array(
    'lack of defensive design' => null,
    'date/time mishandling' => 1,
  ),
  'mitigating' => array(
  ),
  'refs' => array(
    array(
      'title'     => 'Lockheed Martin F-22 Raptor',
      'subtitle'  => 'Notable Accidents',
      'author'    => 'Wikipedia',
      'url'       => 'http://en.wikipedia.org/wiki/Lockheed_Martin_F-22_Raptor#Notable_accidents',
    ),
    array(
      'title'     => 'International Date Line Bug Caused Fighter Aircraft Systems Crash',
      'author'    => 'Jennifer Moebius',
      'url'       => 'http://blog.utest.com/international-date-line-bug-caused-fighter-aircraft-systems-crash/2010/02/',
    ),
    array(
      'title'     => 'F-22 Squadron Shot Down by the International Date Line',
      'author'    => 'Defense Industry Daily',
      'url'       => 'http://www.defenseindustrydaily.com/f22-squadron-shot-down-by-the-international-date-line-03087/',
    ),
    array(
      'title'     => 'Raptors arrive at Kadena',
      'author'    => 'U.S. Air Force',
      'url'       => 'http://www.af.mil/news/story.asp?storyID=123041567',
    ),
  ),
);

