<?php
# ex: set ts=2 et:

$Bugs['f00f'] = array(
  'title' => 'Pentium F00F Bug',
  'when' => '1998',
  'industry' => 'electronics',
  'result' => 'costly operating system engineering effort',
  'cost' => array(
    'deaths' => 0,
    'injuries' => 0,
    'dollars' => 500e6
  ),
  'causes' => array(
    'inadequate testing' => 1,
    'overreliance on automation' => 3,
    'halt and catch fire' => 1,
  ),
  'mitigating' => array(
    'OS defensive efforts successful' => null,
  ),
  'refs' => array(
    array(
      'title'     => 'Pentium F00F Bug',
      'subtitle'  => '',
      'author'    => 'Wikipedia',
      'url'       => 'http://en.wikipedia.org/wiki/Pentium_F00F_bug',
    ),
    array(
      'title'     => 'Invalid Instruction Erratum Overview',
      'subtitle'  => '',
      'author'    => 'Intel',
      'url'       => 'http://www.intel.com/support/processors/pentium/sb/CS-013148.htm',
    ),
    array(
      'title'     => 'Pentium F00F Bug',
      'subtitle'  => '',
      'author'    => 'Robert R. Collins',
      'url'       => 'http://drdobbs.com/architecture-and-design/184410555',
    ),
  ),
);

