<?php
# ex: set ts=2 et:

$Bugs['hms-sheffield-friendly-missile'] = array(
  'title' => 'HMS Sheffield Exocet Missile Mis-classification',
  'when' => 'May 4, 1982',
  'industry' => 'military',
  'result' => array(
    'failure to intercept incoming missile' => 1,
    'ship loss' => 1,
  ),
  'cost' => array(
    'deaths' => 30,
    'injuries' => null,
    'lives-at-risk' => 257,
    'dollars' => null,
    '£' => 23.2e6,
  ),
  'causes' => array(
    'inadequate requirements' => null,
    'unnecessary simplicity' => null,
    'insufficient maintenance' => null,
  ),
  'refs' => array(
    array(
      'title'     => 'HMS Sheffield',
      'author'    => 'Wikipedia',
      'url'       => 'http://en.wikipedia.org/wiki/HMS_Sheffield_(D80)',
    ),
    array(
      'title'     => 'HMS Sheffield Thought Exocet was Friendly',
      'author'    => 'New Scientist',
      'url'       => 'http://books.google.com/books?id=jQEjRCG4E7UC&pg=PA353&lpg=PA353&dq=hms+sheffield+exocet+friendly&source=bl&ots=jOqHj9dew3&sig=_n1jPr2W10ixi_vWZw3rXljC_HQ&hl=en&ei=TlBRTpr3FIjd0QH2iZCUBw&sa=X&oi=book_result&ct=result&resnum=4&ved=0CDQQ6AEwAw#v=onepage&q=hms%20sheffield%20exocet%20friendly&f=false',
    ),
    array(
      'title'     => 'Type 42 Destroyer',
      'author'    => 'Wikipedia',
      'url'       => 'http://en.wikipedia.org/wiki/Type_42_destroyer',
    ),
    array(
      'title'     => 'Research Establishments',
      'author'    => 'UK Parliament',
      'url'       => 'http://hansard.millbanksystems.com/written_answers/1989/oct/23/research-establishments#S6CV0158P0_19891023_CWA_517',
      'reprint'   => 'HC Deb 23 October 1989 vol 158 cc357-8W',
    ),
  ),
);

