<?php
# ex: set ts=2 et:

$Bugs['iran-655'] = array(
  'title' => 'USS Vicennes Mistakenly Shooting Down Iran Air Flight 655',
  'when' => '1988',
  'industry' => 'military',
  'result' => 'aircraft loss',
  'cost' => array(
    'deaths' => 290,
    'injuries' => 0,
    'dollars' => 0
  ),
  'causes' => array(
    'incorrect radio frequency for contact',
  ),
  'refs' => array(
    array(
      'title'     => "1983 Soviet nuclear false alarm incident",
      'subtitle'  => '',
      'author'    => 'Wikipedia',
      'url'       => 'http://en.wikipedia.org/wiki/1983_Soviet_nuclear_false_alarm_incident',
    ),
    array(
      'title'     => "'I Had A Funny Feeling in My Gut'",
      'subtitle'  => '',
      'author'    => 'David Hoffman',
      'url'       => 'http://www.washingtonpost.com/wp-srv/inatl/longterm/coldwar/shatter021099b.htm',
    ),
  ),
);

