<?php
# ex: set ts=2 et:

$Bugs['mariner-1'] = array(
  'title' => 'Mariner-1',
  'when' => 'Jul 22, 1962',
  'industry' => 'aerospace',
  'result' => 'rocket/satellite loss',
  'cost' => array(
    'deaths' => 0,
    'injuries' => 0,
    'dollars' => 50e6
  ),
  'causes' => array(
    'transcription error' => 1,
    'deadline pressure' => 1,
    'inadequate testing' => 1
  ),
  'refs' => array(
    array(
      'title'     => 'Mariner 1',
      'subtitle'  => '',
      'author'    => 'Wikipedia',
      'url'       => 'http://en.wikipedia.org/wiki/Mariner_1',
    ),
    array(
      'title'     => 'Mariner 1',
      'subtitle'  => '',
      'author'    => 'NASA',
      'url'       => 'http://nssdc.gsfc.nasa.gov/nmc/spacecraftDisplay.do?id=MARIN1',
    ),
    array(
      'title'     => 'Space FAQ - Planetary Probe History',
      'author'    => 'Jon Leech <leech@cs.unc.edu>',
      'url'       => 'http://www.faqs.org/faqs/space/probe/',
    ),
  ),
);

