<?php
# ex: set ts=2 et:

$Bugs['mars-rover-priority-inversion'] = array(
  'title' => 'Mars Rover Priority Inversion',
  'when' => '1997',
  'industry' => 'aerospace',
  'result' => array(
  ),
  'cost' => array(
    'deaths' => 0,
    'injuries' => 0,
    'dollars' => null,
    'delay-days' => null,
  ),
  'causes' => array(
    'priority inversion' => 1,
  ),
  'mitigating' => array(
    'enabled debug features allowed correction ' => null,
  ),
  'refs' => array(
    array(
      'title'     => 'What Really Happened On Mars?',
      'author'    => 'Glenn E Reeves',
      'url'       => 'http://research.microsoft.com/en-us/um/people/mbj/Mars_Pathfinder/Authoritative_Account.html',
    ),
  ),
);

