<?php
# ex: set ts=2 et:

$Bugs['mars-polar-lander'] = array(
  'title' => 'Mars Polar Lander',
  'when' => 'Jan 3, 1999',
  'industry' => 'aerospace',
  'result' => 'satellite loss',
  'cost' => array(
    'deaths' => 0,
    'injuries' => 0,
    'dollars' => 150e6
  ),
  'causes' => array(
    'faulty signal analysis' => 3,
    'unnecessary complexity' => 3,
  ),
  'refs' => array(
    array(
      'title'     => 'Mars Polar Lander',
      'author'    => 'Wikipedia',
      'url'       => 'http://en.wikipedia.org/wiki/Mars_Polar_Lander',
    ),
    array(
      'title'     => 'Mars Climate Orbiter/Mars Polar Lander - Mission Overview',
      'author'    => 'NASA',
      'url'       => 'http://mars.jpl.nasa.gov/msp98/mission_overview.html',
    ),
    array(
      'title'     => 'The Role of Software in Recent Aerospace Accidents',
      'author'    => 'Nancy G. Leveson',
      'url'       => 'http://sunnyday.mit.edu/accidents/issc01.pdf',
    ),
    array(
      'title'     => 'Mars Polar Lander: Clues From the Crash Site',
      'author'    => 'NASA',
      'url'       => 'http://www.space.com/1153-mars-polar-lander-clues-crash-site.html',
    ),
  ),
);

