<?php
# ex: set ts=2 et:

$Bugs['mars-climate-orbiter'] = array(
  'title' => 'Mars Climate Orbiter',
  'when' => 'Sep 23, 1999',
  'industry' => 'aerospace',
  'result' => 'satellite loss',
  'cost' => array(
    'deaths' => 0,
    'injuries' => 0,
    'dollars' => 300e6
  ),
  'causes' => array(
    'unit conversion' => 2,
    'complacency' => 3,
  ),
  'refs' => array(
    array(
      'title'     => 'Mars Climate Orbiter',
      'author'    => 'Wikipedia',
      'url'       => 'http://en.wikipedia.org/wiki/Mars_Climate_Orbiter',
    ),
    array(
      'title'     => 'MARS CLIMATE ORBITER TEAM FINDS LIKELY CAUSE OF LOSS',
      'author'    => 'Mary Hardin',
      'url'       => 'http://www.jpl.nasa.gov/news/releases/99/mcoloss1.html',
    ),
    array(
      'title'     => 'Systemic Factors in Software-Related Accidents',
      'author'    => 'Nancy G. Leveson',
      'url'       => 'http://sunnyday.mit.edu/accidents/space2001.pdf',
    ),
    array(
      'title'     => 'Metric mishap caused loss of NASA orbiter',
      'author'    => 'CNN',
      'url'       => 'http://articles.cnn.com/1999-09-30/tech/9909_30_mars.metric.02_1_climate-orbiter-spacecraft-team-metric-system?_s=PM:TECH',
    ),
  ),
);

