<?php
# ex: set ts=2 et:

$Bugs['monolithic-kernel'] = array(
  'title' => 'The Monolithic Kernel',
  'when' => '2006-present',
  'industry' => 'software',
  'result' => array(
    'the software security industry' => null,
    'rootkits' => null,
  ),
  'cost' => array(
    'deaths' => 0,
    'injuries' => 0,
    'dollars' => 500e9
  ),
  'causes' => array(
    'unrealistic risk assessment' => null,
    'premature optimization' => null,
    'performance over stability' => null,
    'deadline pressure' => null,
  ),
  'refs' => array(
    array(
      'title'     => 'Monolithic kernel',
      'subtitle'  => '',
      'author'    => 'Wikipedia',
      'url'       => 'http://en.wikipedia.org/wiki/Monolithic_kernel',
    ),
    array(
      'title'     => 'Microkernel',
      'subtitle'  => '',
      'author'    => 'Wikipedia',
      'url'       => 'http://en.wikipedia.org/wiki/Microkernel',
    ),
    array(
      'title'     => 'Intel Core (microarchitecture)',
      'subtitle'  => '',
      'author'    => 'Wikipedia',
      'url'       => 'http://en.wikipedia.org/wiki/Core_(microarchitecture)',
    ),
  ),
);

