<?php
# ex: set ts=2 et:

$Bugs[basename(__FILE__)] = array(
  'title' => 'Panama Radiation Therapy Overdose',
  'when' => '2000',
  'industry' => 'medical',
  'summary' => '',
  'result' => array(
    'radiation overdose (10-110%)' => 1,
  ),
  'cost' => array(
    'deaths' => 18,
    'injuries' => 10,
    'dollars' => null,
  ),
  'causes' => array(
    'overreliance on automation' => 1,
    'inconsistent output' => 1,
    'double counting' => 1,
    'inadequate testing' => 1,
  ),
  'mitigating' => array(
  ),
  'refs' => array(
    array(
      'title'     => 'Overexposure of radiation therapy patients in Panama',
      'subtitle'  => 'Problem recognition and follow-up measures',
      'author'    => 'Cari Borras',
      'url'       => 'http://journal.paho.org/uploads/1162234952.pdf',
    ),
    array(
      'title'     => "'We Did Nothing Wrong'",
      'author'    => 'John McCormick',
      'url'       => 'http://www.baselinemag.com/c/a/Projects-Processes/We-Did-Nothing-Wrong/',
    ),
  ),
);

