<?php
# ex: set ts=2 et:

$Bugs['phobos'] = array(
  'title' => 'Фобос/Phobos Program',
  'when' => '1988-1989',
  'industry' => 'aerospace',
  'result' => array(
    'communication lost' => 2,
    'craft loss' => 2,
  ),
  'cost' => array(
    'deaths' => 0,
    'injuries' => 0,
    'dollars' => null,
  ),
  'causes' => array(
    'deadline pressure' => 2,
    'test software left enabled' => 2,
    'typo' => 2,
  ),
  'mitigating' => array(
  ),
  'refs' => array(
    array(
      'title'     => 'Phobos Program',
      'author'    => 'Wikipedia',
      'url'       => 'http://en.wikipedia.org/wiki/Phobos_program',
    ),
    array(
      'title'     => 'Phobos 1 & 2 computer failures',
      'author'    => 'Ralph Hartley <hartley@aic.nrl.navy.mil>',
      'url'       => 'http://catless.ncl.ac.uk/Risks/9.24.html#subj3',
      'reprint'   => 'SCIENCE Vol 245, 8 September 1989 p1045',
    ),
  ),
);

