<?php
# ex: set ts=2 et:

$Bugs['prius-brake-problem'] = array(
  'title' => 'Prius Anti-Lock Brake Recall',
  'when' => '2010',
  'industry' => 'automotive',
  'result' => array(
    '77 incidents' => 1,
    'bad PR' => 1,
    'costly product recall' => 1,
  ),
  'cost' => array(
    'deaths' => 0,
    'injuries' => 0,
    'dollars' => null,
  ),
  'causes' => array(
    'unspecified software error' => 1,
  ),
  'refs' => array(
    array(
      'title'     => 'Toyota: Software to blame for Prius brake problems',
      'author'    => 'CNN',
      'url'       => 'http://www.cnn.com/2010/WORLD/asiapcf/02/04/japan.prius.complaints/index.html',
    ),
    array(
      'title'     => '2009-2011 Toyota vehicle recalls',
      'subtitle'  => 'Anti-lock brake software recall',
      'author'    => 'Wikipedia',
      'url'       => 'http://en.wikipedia.org/wiki/2009%E2%80%932011_Toyota_vehicle_recalls#Anti-lock_brake_software_recall',
    ),
  ),
);

