<?php
# ex: set ts=2 et:

$Bugs['prius-brake-problem'] = array(
  'title' => 'Prius Anti-Lock Brake Recall',
  'when' => '2010',
  'industry' => 'automotive',
  'result' => array(
    '77 incidents' => 1,
    'bad PR' => 1,
    'costly product recall' => 1,
    'class-action lawsuit' => 1,
  ),
  'cost' => array(
    'deaths' => 0,
    'injuries' => 0,
    'dollars' => 160e6,
    'recalls' => 100e3,
  ),
  'causes' => array(
    'unspecified software error' => 1,
    #'complexity' => 3, # regenerative braking involved
  ),
  'refs' => array(
    array(
      'title'     => 'Toyota: Software to blame for Prius brake problems',
      'author'    => 'CNN',
      'url'       => 'http://www.cnn.com/2010/WORLD/asiapcf/02/04/japan.prius.complaints/index.html',
    ),
    array(
      'title'     => '2009-2011 Toyota vehicle recalls',
      'subtitle'  => 'Anti-lock brake software recall',
      'author'    => 'Wikipedia',
      'url'       => 'http://en.wikipedia.org/wiki/2009%E2%80%932011_Toyota_vehicle_recalls#Anti-lock_brake_software_recall',
    ),
    array(
      'title'     => 'NHTSA Tracking Braking Loss on Prius Hybrids',
      'author'    => 'Ken Zino',
      'url'       => 'http://www.thedetroitbureau.com/2009/12/nhtsa-tracking-braking-loss-on-prius-hybrids/',
    ),
    array(
      'title'     => 'U.S. Department of Transportation Responds to Third Toyota Recall',
      'author'    => 'U.S. DOT',
      'url'       => 'http://www.nhtsa.gov/PR/DOT-25-10',
    ),
    array(
      'title'     => "Experts: Price of Toyota's troubles will soar",
      'author'    => 'Hans Greimel <hgreimel@crain.com>',
      'url'       => 'http://www.autonews.com/apps/pbcs.dll/article?AID=/20100412/RETAIL02/304129969/1316/mobile&template=art4',
    ),
  ),
);

