<?php
# ex: set ts=2 et:

$Bugs[basename(__FILE__)] = array(
  'title' => 'TOMS Ozone Layer Depletion Overlooked',
  'when' => '1978-1985',
  'industry' => 'aerospace',
  'summary' => '',
  'result' => array(
    'ozone layer depletion' => 1,
  ),
  'cost' => array(
    'deaths' => 0,
    'injuries' => 0,
    'dollars' => null,
    'delay-years' => 8,
  ),
  'causes' => array(
    'unexpected results ignored' => null,
    'edge case' => null,
  ),
  'mitigating' => array(
    'secondary source of information' => null,
    'eventually realized' => null,
  ),
  'refs' => array(
    array(
      'title'     => 'Research Satellites for Atmospheric Sciences, 1978-Present',
      'author'    => 'NASA',
      'url'       => 'http://earthobservatory.nasa.gov/Features/RemoteSensingAtmosphere/remote_sensing5.php',
    ),
    array(
      'title'     => '10 historical software bugs with extreme consequences',
      'author'    => 'Pingdom',
      'url'       => 'http://royal.pingdom.com/2009/03/19/10-historical-software-bugs-with-extreme-consequences/',
    ),
  ),
);

