<?php
# ex: set ts=2 et:

$Bugs['v-22-osprey'] = array(
  'title' => 'V-22 Osprey Crash',
  'when' => 'Dec 11, 2000',
  'industry' => 'military',
  'result' => 'aircraft crash',
  'cost' => array(
    'deaths' => 4,
    'injuries' => 0,
    'dollars' => null
  ),
  'causes' => array(
    'confusing output' => 2,
  ),
  'refs' => array(
    array(
      'title'     => 'Accidents and incidents involving the V-22 Osprey',
      'subtitle'  => '',
      'author'    => 'Wikipedia',
      'url'       => 'http://en.wikipedia.org/wiki/Accidents_and_incidents_involving_the_V-22_Osprey#December_2000',
    ),
    array(
      'title'     => "Saving the Pentagon's Killer Chopper-Plane",
      'subtitle'  => '',
      'author'    => 'Ron Berler',
      'url'       => 'http://www.wired.com/wired/archive/13.07/osprey.html?pg=3&topic=osprey&topic_set=',
    ),
  ),
);

